name = "worthwhile_emerald_octopus-fa6b"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "worthwhile_emerald_octopus-fa6b_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "worthwhile_emerald_octopus-fa6b.wasm"
command = "npm run build:release"
